# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170914_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
