# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categort',
            field=models.CharField(default='后端', max_length=20),
        ),
    ]
