# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': ('轮播图',), 'verbose_name_plural': ('轮播图',)},
        ),
        migrations.AlterModelOptions(
            name='emailverfyrecord',
            options={'verbose_name': ('邮箱验证码',), 'verbose_name_plural': ('邮箱验证码',)},
        ),
    ]
