# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170921_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '更改邮箱')], max_length=30, verbose_name='验证码类型'),
        ),
    ]
